function avtoduma(){var fb='',R=' top: -1000px;',ob='" for "gwt:onLoadErrorFn"',mb='" for "gwt:onPropertyErrorFn"',$='");',pb='#',sc='.cache.js',rb='/',xb='//',Zb='075A03402A745A0E462C26280A3EBAE6',$b='099918A191EBBF254A0B9AD2517A7B76',_b='0FFD415D0687AF47A77CB17C441F347C',ac='3139F08C7402C1CB1E8A5A5F8A4B5E93',bc='352C8B0DFA35B4EFCECB665018370D2E',cc='3B1AD963204913E2400020207B6D21EB',dc='4EA032BC51EC99191AF455BF6DB957C8',ec='507BA3BB8A387B0CE8AFA5F172720E7E',fc='5966C8385CB9C2FADA574BE4C7EE6C7E',gc='661CB30702226FE2FA2CBD244AA53B62',hc='73CEA4E25518983FDB22D800D86D3A01',ic='8141C5437C6929DFAAF1789D69B5763A',jc='83DDFDAD0EA96D3647DB5132046BE8A6',kc='8B1F17777B9D0BFB17A323754C226488',lc='90840D683D1526EEB1A6CC6E2C1C9804',mc='9F57F5A611FC300226872A403627C361',rc=':',gb='::',S='<html><head><\/head><body><\/body><\/html>',jb='=',qb='?',nc='A442490AB9582E3DF0F6221B73B1F1ED',oc='AD3A03A463E5E67CDC03C8CD953E437E',pc='B16F59D86AA8A87E3D0BA41F0E81CAA3',lb='Bad handler "',Y='Chrome',X='DOMContentLoaded',M='DUMMY',qc='E34E0B2FC7D1CC21F6A5EA29E0388C8E',zb='android',Bb='android_tablet',K='avtoduma',Yb='avtoduma.devmode.js',vb='avtoduma.nocache.js',eb='avtoduma::',wb='base',ub='baseUrl',H='begin',Hb='blackberry',N='body',G='bootstrap',tb='clear.cache.gif',ib='content',Ib='desktop',uc='end',Z='eval("',Ub='gecko',Vb='gecko1_8',I='gwt.codesvr.avtoduma=',J='gwt.codesvr=',nb='gwt:onLoadErrorFn',kb='gwt:onPropertyErrorFn',hb='gwt:property',bb='head',Tb='ie6',Sb='ie8',Rb='ie9',O='iframe',sb='img',Cb='ipad',Db='ipad_retina',Eb='iphone',Fb='ipod',U='javascript',P='javascript:""',tc='loadExternalRefs',cb='meta',yb='mgwt.os',Ab='mobile',Jb='mobile.user.agent',Kb='mobilesafari',ab='moduleRequested',_='moduleStartup',Qb='msie',db='name',Lb='not_mobile',Nb='opera',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Gb='retina',Pb='safari',T='script',Xb='selectingPermutation',L='startup',W='undefined',Wb='unknown',Mb='user.agent',V='var $wnd = window.parent;',Ob='webkit';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
avtoduma.__sendStats=r;avtoduma.__moduleName=K;avtoduma.__errFn=null;avtoduma.__moduleBase=M;avtoduma.__softPermutationId=0;avtoduma.__computePropValue=null;avtoduma.__getPropMap=null;avtoduma.__gwtInstallCode=function(){};avtoduma.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close();var b=v.getElementsByTagName(N)[0];var c=v.createElement(T);c.language=U;var d=V;c.text=d;b.appendChild(c)}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(T);g.language=U;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(T);g.language=U;g.text=c[i];e.appendChild(g);d(e,g)}}}
avtoduma.onScriptDownloaded=function(a){l(function(){m(a)})};r(_,ab);var n=p.createElement(T);n.src=k;p.getElementsByTagName(bb)[0].appendChild(n)}
avtoduma.__startLoadingFragment=function(a){return C(a)};avtoduma.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(T);c.language=U;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(cb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(db),k;if(j){j=j.replace(eb,fb);if(j.indexOf(gb)>=0){continue}if(j==hb){k=i.getAttribute(ib);if(k){var l,m=k.indexOf(jb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=fb}c[j]=l}}else if(j==kb){k=i.getAttribute(ib);if(k){try{d=eval(k)}catch(a){alert(lb+k+mb)}}}else if(j==nb){k=i.getAttribute(ib);if(k){try{e=eval(k)}catch(a){alert(lb+k+ob)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;avtoduma.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(pb);if(b==-1){b=a.length}var c=a.indexOf(qb);if(c==-1){c=a.length}var d=a.lastIndexOf(rb,Math.min(c,b));return d>=0?a.substring(0,d+1):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(sb);b.src=a+tb;a=e(b.src)}return a}
function g(){var a=t(ub);if(a!=null){return a}return fb}
function h(){var a=p.getElementsByTagName(T);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(vb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=p.getElementsByTagName(wb);if(a.length>0){return a[a.length-1].href}return fb}
function j(){var a=p.location;return a.href==a.protocol+xb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return avtoduma.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[yb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(zb)!=-1){if(a.indexOf(Ab)!=-1){return zb}else{return Bb}}if(a.indexOf(Cb)!=-1){if(window.devicePixelRatio>=2){return Db}return Cb}if(a.indexOf(Eb)!=-1||a.indexOf(Fb)!=-1){if(window.devicePixelRatio>=2){return Gb}return Eb}if(a.indexOf(Hb)!=-1){return Hb}return Ib}();return b}};i[yb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};j[Jb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Kb:Lb};i[Jb]={mobilesafari:0,not_mobile:1};j[Mb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Nb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=9}())return Rb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=8}())return Sb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Tb;if(function(){return b.indexOf(Ub)!=-1}())return Vb;return Wb};i[Mb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};avtoduma.__getPropMap=function(){var a={};for(var b in i){a[b]=k(b)}return a};avtoduma.__computePropValue=k;o.__gwt_activeModules[K].bindings=avtoduma.__getPropMap;r(G,Xb);if(q()){return C(Yb)}var l;try{h([Ib,Lb,Sb],Zb);h([Ib,Lb,Rb],$b);h([zb,Lb,Pb],_b);h([Eb,Kb,Pb],ac);h([Db,Kb,Pb],bc);h([Bb,Lb,Pb],cc);h([Bb,Kb,Pb],dc);h([Ib,Lb,Nb],ec);h([Hb,Kb,Pb],fc);h([Gb,Kb,Pb],gc);h([Ib,Kb,Pb],hc);h([Gb,Lb,Pb],ic);h([Ib,Lb,Pb],jc);h([Hb,Lb,Pb],kc);h([Cb,Kb,Pb],lc);h([Cb,Lb,Pb],mc);h([Ib,Lb,Vb],nc);h([Db,Lb,Pb],oc);h([zb,Kb,Pb],pc);h([Eb,Lb,Pb],qc);l=f[k(yb)][k(Jb)][k(Mb)];var m=l.indexOf(rc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}avtoduma.__softPermutationId=g;return C(l+sc)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(tc,H);r(tc,uc)}
A();avtoduma.__moduleBase=B();u[K].moduleBase=avtoduma.__moduleBase;var F=D();E();r(G,uc);z(F);return true}
avtoduma.succeeded=avtoduma();